-- Ist absichtlich getrennt
-- wird von Texte / Reset verwendet

DROP TABLE IF EXISTS `#__system_texte`;
CREATE TABLE IF NOT EXISTS `#__system_texte` (
  `id` int(11) NOT NULL auto_increment,
  `art` varchar(25) collate utf8_unicode_ci NOT NULL,
  `lang` varchar(25) collate utf8_unicode_ci NOT NULL,
  `betreff` varchar(255) collate utf8_unicode_ci NOT NULL,
  `text` text collate utf8_unicode_ci NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

INSERT INTO `#__system_texte` (`id`, `art`, `lang`, `betreff`, `text`) VALUES
(1, 'anmeldung', 'deu', 'Anmeldung', '<p>[Shopname]<br /> <br />Vielen Dank f&uuml;r Ihre Anmeldung, [Anrede_Kunde] [Nachname_Kunde],<br />Zum Verifizieren Klicken Sie bitte auf diesen Link:<br /> [Verifizierungslink]</p>'),
(2, 'anmeldung', 'eng', 'Verification', '<p>[Shopname]<br /><br />Thanks for subscribing, [Anrede_Kunde] [Nachname_Kunde],<br />to verify, please click on this link: <br />[Verifizierungslink]</p>'),

(3, 'pw_vergessen', 'deu', 'Passwort vergessen', '<p>[Shopname]<br /> <br /> Bitte Klicken Sie auf diesen Link:<br /> [Verifizierungslink]<br />und geben Ihr neues Passwort ein.</p>'),
(4, 'pw_vergessen', 'eng', 'Forgot password', '<p>[Shopname]<br /><br />Please click on this link:<br />[Verifizierungslink]<br />and enter your new password.</p>'),

(5, 'anfrage_best', 'deu', 'Bestätigung Ihrer Anfrage', '<p>Vielen Dank f&uuml;r Ihre Anfrage, [Anrede_Kunde] [Nachname_Kunde].<br /> Nach Pr&uuml;fung Ihrer Anfrage erhalten Sie eine Bestellbest&auml;tigung.<br /><br />Bestellnummer: [Bestellnummer]<br />Zahlungsart: [Zahlungsart]</p><table border="0"><tbody><tr><td style="width: 300px;"><strong>Rechnungsanschrift</strong><br /><br /> [Email_Kunde]<br />[Vorname_Kunde] [Nachname_Kunde]<br /> [Firma_Kunde]<br /> [Strasse_Kunde]<br /> [PLZ_Kunde] [Ort_Kunde]<br /> [Bundesland_Kunde]<br /> [Staat_Kunde]<br /><br />[USTID]<br />Tel: [Telefonnummer]</td><td style="width: 300px;"><strong>Lieferanschrift</strong><br /><br />[Vorname_KundeL] [Nachname_KundeL]<br /> [Firma_KundeL]<br /> [Postnummer_KundeL]<br /> [Strasse_KundeL]<br /> [PLZ_KundeL] [Ort_KundeL]<br /> [Bundesland_KundeL]<br /> [Staat_KundeL]<br /><br /><br /><br /></td></tr></tbody></table><p>[Artikel]<br /> <br /> [Summe]<br /><br />[Nachricht_Kunde]<br /><br /> Mit freundlichen Gr&uuml;&szlig;en<br /> [Shopname]</p><p><br />[Widerrufsbelehrung]</p>'),
(6, 'anfrage_best', 'eng', 'Confirmation of your request', '<p>Thank you for your request, [Anrede_Kunde] [Nachname_Kunde].<br />After considering your request you will receive an order confirmation.<br /><br />Order number: [Bestellnummer]<br />Payment method: [Zahlungsart]<br /><br /></p>
<table border="0"><tbody><tr><td style="width: 300px;"><strong>Invoice address</strong><br /><br />[Email_Kunde]<br />[Vorname_Kunde] [Nachname_Kunde]<br />[Firma_Kunde]<br />[Strasse_Kunde]<br />[PLZ_Kunde] [Ort_Kunde]<br />[Bundesland_Kunde]<br />[Staat_Kunde]<br /><br />[USTID]<br />Fon: [Telefonnummer]</td>
<td style="width: 300px;"><strong>Delivery address</strong><br /><br />[Vorname_KundeL] [Nachname_KundeL]<br />[Firma_KundeL]<br />[Postnummer_KundeL]<br />[Strasse_KundeL]<br />[PLZ_KundeL] [Ort_KundeL]<br />[Bundesland_KundeL]<br />[Staat_KundeL]<br /><br /><br /><br /></td></tr></tbody></table><p><br />[Artikel]<br /><br />[Summe]<br /><br />[Nachricht_Kunde]<br /><br />Best regards<br />[Shopname]</p><p><br />[Widerrufsbelehrung]</p>'),

(7, 'best_best', 'deu', 'Bestellbestätigung', '<p>Vielen Dank f&uuml;r Ihre Bestellung, [Anrede_Kunde] [Nachname_Kunde].<br />Die Waren sind auf Lager und wir best&auml;tigen Ihre Bestellung.<br /><br />Bestellnummer: [Bestellnummer]<br />Zahlungsart: [Zahlungsart]</p><table border="0"><tbody><tr><td style="width: 300px;"><strong>Rechnungsanschrift</strong><br /><br />[Email_Kunde]<br />[Vorname_Kunde] [Nachname_Kunde]<br />[Firma_Kunde]<br />[Strasse_Kunde]<br />[PLZ_Kunde] [Ort_Kunde]<br />[Bundesland_Kunde]<br />[Staat_Kunde]<br /><br />[USTID]<br />Tel: [Telefonnummer]</td><td style="width: 300px;"><strong>Lieferanschrift</strong><br /><br />[Vorname_KundeL] [Nachname_KundeL]<br />[Firma_KundeL]<br />[Postnummer_KundeL]<br />[Strasse_KundeL]<br />[PLZ_KundeL] [Ort_KundeL]<br />[Bundesland_KundeL]<br />[Staat_KundeL]<br /><br /><br /><br /></td></tr></tbody></table><p>[Artikel]<br /><br />[Summe]<br /><br />[Nachricht_Admin]<br /><br /><br />&Uuml;berweisungsdaten:<br />[Ueberweisungsdaten]<br />[Zahlungsart_Text]<br />Bitte geben Sie beim Verwendungszweck Ihre Bestellnummer an: [Bestellnummer]<br />Nachdem Ihre Zahlung eingegangen ist, senden wir Ihnen Artikel &amp; Rechnung zu.<br />Vielen Dank!<br /><br />Ihren Status k&ouml;nnen Sie unter <a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a><br />Benutzer: [Email_Kunde]<br /><br />Mit freundlichen Gr&uuml;&szlig;en<br />[Shopname]</p><p><br />[Widerrufsbelehrung]</p>'),
(8, 'best_best', 'eng', 'Order confirmation', '<p>Thank you for your order, [Anrede_Kunde] [Nachname_Kunde].<br />The goods are in stock and we confirm your order.<br /><br /><span class="tlid-translation translation" lang="en"><span class="" title="">Order number:</span></span> [Bestellnummer]<br /><span class="tlid-translation translation" lang="en"><span class="" title="">Payment method</span></span>: [Zahlungsart]<br /><br /></p><table border="0"><tbody>
<tr><td style="width: 300px;"><strong>Invoice address</strong><br /><br />[Email_Kunde]<br />[Vorname_Kunde] [Nachname_Kunde]<br />[Firma_Kunde]<br />[Strasse_Kunde]<br />[PLZ_Kunde] [Ort_Kunde]<br />[Bundesland_Kunde]<br />[Staat_Kunde]<br /><br />[USTID]<br />Fon: [Telefonnummer]</td><td style="width: 300px;"><strong>Delivery address</strong><br /><br />[Vorname_KundeL] [Nachname_KundeL]<br />[Firma_KundeL]<br />[Postnummer_KundeL]<br />[Strasse_KundeL]<br />[PLZ_KundeL] [Ort_KundeL]<br />[Bundesland_KundeL]<br />[Staat_KundeL]<br /><br /><br /><br /></td></tr></tbody></table><p><br />[Artikel]<br /><br />[Summe]<br /><br />[Nachricht_Admin]<br /><br /><br />Transfer data:<br />[Ueberweisungsdaten]<br />[Zahlungsart_Text]<br />Please indicate your order number for the intended purpose: [Bestellnummer]<br />After your payment has been received, we will send you the article and invoice.<br />Thank you!<br /><br />See your status under <a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a><br />User: [Email_Kunde]<br /><br />Best regards<br />[Shopname]</p><p><br />[Widerrufsbelehrung]</p>'),

(9, 'best_admin', 'deu', 'Bestellung über [Shopname]', '<p>Es ist eine Bestellung im Shop [Shopname] eingegangen.</p><p>Bestellnummer: [Bestellnummer]<br />Zahlungsart: [Zahlungsart]<br /><br /></p><table border="0"><tbody><tr><td style="width: 300px;"><strong>Rechnungsanschrift</strong><br /><br />[Email_Kunde]<br />[Vorname_Kunde] [Nachname_Kunde]<br />[Firma_Kunde]<br />[Strasse_Kunde]<br />[PLZ_Kunde] [Ort_Kunde]<br />[Bundesland_Kunde]<br />[Staat_Kunde]<br /><br />[USTID]<br />Tel: [Telefonnummer]</td><td style="width: 300px;"><strong>Lieferanschrift</strong><br /><br />[Vorname_KundeL] [Nachname_KundeL]<br />[Firma_KundeL]<br />[Postnummer_KundeL]<br />[Strasse_KundeL]<br />[PLZ_KundeL] [Ort_KundeL]<br />[Bundesland_KundeL]<br />[Staat_KundeL]<br /><br /><br /><br /></td></tr></tbody></table><p><br />Bestellte Artikel:<br />[Artikel]<br /><br />[Summe]<br /><br />[Nachricht_Kunde]</p>'),
(10, 'best_admin', 'eng', 'Order over [Shopname]', '<p>It has received an order in the shop [Shopname].</p><p>Order nummber: [Bestellnummer]<br />Payment method: [Zahlungsart]<br /><br /></p><table border="0"><tbody><tr><td style="width: 300px;"><strong>Invoice address</strong><br /><br />[Email_Kunde]<br />[Vorname_Kunde] [Nachname_Kunde]<br />[Firma_Kunde]<br />[Strasse_Kunde]<br />[PLZ_Kunde] [Ort_Kunde]<br />[Bundesland_Kunde]<br />[Staat_Kunde]<br /><br />[USTID]<br />Fon: [Telefonnummer]</td><td style="width: 300px;"><strong>Delivery address</strong><br /><br />[Vorname_KundeL] [Nachname_KundeL]<br />[Firma_KundeL]<br />[Postnummer_KundeL]<br />[Strasse_KundeL]<br />[PLZ_KundeL] [Ort_KundeL]<br />[Bundesland_KundeL]<br />[Staat_KundeL]<br /><br /><br /><br /></td></tr></tbody></table><p><br />Ordered items:<br />[Artikel]<br /><br />[Summe]<br /><br />[Nachricht_Kunde]</p>'),

(11, 'rechnung', 'deu', 'Versandbestätigung', '<p>Hallo [Anrede_Kunde] [Nachname_Kunde],<br /><br />Ihre Ware wurde soeben versendet. Ihre Rechnung befindet sich im Anhang.<br />Ihre Bestellungen und Rechnungen k&ouml;nnen Sie auch online unter<br /><a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a> einsehen.<br />Benutzer: [Email_Kunde]<br /><br />[Nachricht_Admin]<br /><br />Mit freundlichen Gr&uuml;&szlig;en<br />[Shopname]</p>'),
(12, 'rechnung', 'eng', 'Order confirmation', '<p>Hello [Anrede_Kunde] [Nachname_Kunde],<br /><br />Your merchandise has just shipped. Your statement is annexed.<br />Your orders and invoices You can also view online:<br /><a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a><br />User: [Email_Kunde]<br /><br />[Nachricht_Admin]<br /><br />Best regards<br /><br />[Shopname]</p>'),

(13, 'bewertung', 'deu', 'Bestellung über [Shopname]', '<p>Hallo [Anrede_Kunde] [Nachname_Kunde],<br /> <br />vielen Dank, dass Sie bei uns eingekauft haben.<br />Haben Sie noch Fragen zur Bestellung? Wir stehen Ihnen gern zur Verfügung.<br />Bitte bewerten Sie kurz unseren Onlineshop und klicken dazu auf das Siegel:<br /> <br /><a title="Shopsiegel" href="https://siegel.kanpaiclassic.com/" target="_blank"><img src="https://siegel.kanpaiclassic.com/siegel/siegel2.png" alt="Shopsiegel" border="0" /></a><br /> <br />Viele Gr&uuml;&szlig;e<br /> <br />[Shopname]</p>'),
(14, 'bewertung', 'eng', 'Order over [Shopname]', '<p>Hello [Anrede_Kunde] [Nachname_Kunde],<br /><br />thank you for shopping with us.<br />Do you have any questions about ordering? We are at your disposal.<br />Please briefly rate our online shop and click on the seal:<br /><br /><a title="Shopsiegel" href="https://siegel.kanpaiclassic.com/" target="_blank" rel="noopener"><img src="https://siegel.kanpaiclassic.com/siegel/siegel2.png" alt="Shopsiegel" border="0" /></a><br /><br />Best regards<br /><br />[Shopname]</p>'),

(15, 'gutschrift', 'deu', 'Sie haben eine Gutschrift erhalten!', '<p>Hallo [Anrede_Kunde] [Nachname_Kunde],<br /> <br />als Dankesch&ouml;n f&uuml;r Ihren Einkauf erhalten Sie von uns eine Gutschrift in H&ouml;he von [Gutschrift] Euro.<br />Die Gutschrift wird automatisch bei der n&auml;chsten Bestellung verrechnet.<br /><a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a><br />Benutzer: [Email_Kunde]<br /><br /> <br />Viele Gr&uuml;&szlig;e<br /> <br />[Shopname]</p>'),
(16, 'gutschrift', 'eng', 'You will receive a credit!', '<p>Hello [Anrede_Kunde] [Nachname_Kunde],<br /><br />as a thank you for your purchase you will receive a credit of [Gutschrift] euros from us.<br />The credit is automatically applied to the next order.<br /><a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a><br />User: [Email_Kunde]<br /><br /><br />Best regards<br /><br />[Shopname]</p>'),

(17, 'gutschein1', 'deu', 'Jetzt Gutschein einlösen!', '<p>Liebe Kunden,<br /> <br />Sie erhalten von uns einen Gutschein in Höhe von [Prozent_Hauptwaehrung].<br />Sie können diesen auf <a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a> einlösen.<br />Ihr Gutschein-Code: [Gutschein_Code]<br /><br />Viele Gr&uuml;&szlig;e<br /> <br />[Shopname]</p>'),
(18, 'gutschein1', 'eng', 'Redeem coupon now!', '<p>Dear customers,<br /><br />You will get a coupon of [Prozent_Hauptwaehrung].<br />You can redeem on <a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a><br />Your coupon code: [Gutschein_Code]<br /><br />Best regards<br /><br />[Shopname]</p>'),

(19, 'gutschein2', 'deu', 'Jetzt Gutschein einlösen!', '<p>Liebe Kunden,<br /> <br />Sie erhalten von uns einen Gutschein in Höhe von [Prozent_Hauptwaehrung].<br />Sie können diesen auf <a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a> einlösen.<br />Ihr Gutschein-Code: [Gutschein_Code]<br /><br />Viele Gr&uuml;&szlig;e<br /> <br />[Shopname]</p>'),
(20, 'gutschein2', 'eng', 'Redeem coupon now!', '<p>Dear customers,<br /><br />You will get a coupon of [Prozent_Hauptwaehrung].<br />You can redeem on <a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a><br />Your coupon code: [Gutschein_Code]<br /><br />Best regards<br /><br />[Shopname]</p>'),

(21, 'gutschein3', 'deu', 'Jetzt Gutschein einlösen!', '<p>Liebe Kunden,<br /> <br />Sie erhalten von uns einen Gutschein in Höhe von [Prozent_Hauptwaehrung].<br />Sie können diesen auf <a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a> einlösen.<br />Ihr Gutschein-Code: [Gutschein_Code]<br /><br />Viele Gr&uuml;&szlig;e<br /> <br />[Shopname]</p>'),
(22, 'gutschein3', 'eng', 'Redeem coupon now!', '<p>Dear customers,<br /><br />You will get a coupon of [Prozent_Hauptwaehrung].<br />You can redeem on <a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a><br />Your coupon code: [Gutschein_Code]<br /><br />Best regards<br /><br />[Shopname]</p>'),

(23, 'gutschein4', 'deu', 'Jetzt Gutschein einlösen!', '<p>Liebe Kunden,<br /> <br />Sie erhalten von uns einen Gutschein in Höhe von [Prozent_Hauptwaehrung].<br />Sie können diesen auf <a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a> einlösen.<br />Ihr Gutschein-Code: [Gutschein_Code]<br /><br />Viele Gr&uuml;&szlig;e<br /> <br />[Shopname]</p>'),
(24, 'gutschein4', 'eng', 'Redeem coupon now!', '<p>Dear customers,<br /><br />You will get a coupon of [Prozent_Hauptwaehrung].<br />You can redeem on <a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a><br />Your coupon code: [Gutschein_Code]<br /><br />Best regards<br /><br />[Shopname]</p>'),

(25, 'gutschein5', 'deu', 'Jetzt Coupon einlösen!', '<p>Liebe Kunden,<br /> <br />Sie erhalten von uns eine Gutschrift in Höhe von [Prozent_Hauptwaehrung].<br />Sie können diesen auf <a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a> einlösen.<br />Ihr Coupon-Code lautet: [Gutschein_Code]<br /><br />Viele Gr&uuml;&szlig;e<br /> <br />[Shopname]</p>'),
(26, 'gutschein5', 'eng', 'Redeem coupon now!', '<p>Dear customers,<br /><br />You will get a coupon of [Prozent_Hauptwaehrung].<br />You can redeem on <a href="[SHOPDOMAIN]/login">[SHOPDOMAIN]/login</a><br />Your coupon code: [Gutschein_Code]<br /><br />Best regards<br /><br />[Shopname]</p>'),

(27, 'download', 'deu', 'Ihr Download steht bereit', '<p>Hallo [Anrede_Kunde] [Nachname_Kunde],</p><br /><p>vielen Dank f&uuml;r Ihren Kauf. Sie k&ouml;nnen hier Ihre Datei downloaden:<br />[Downloadlink]</p>'),
(28, 'download', 'eng', 'Your download is ready', '<p>Hello [Anrede_Kunde] [Nachname_Kunde],<br /><br /></p>
<p>Thank you for your purchase. You can download your file here:<br />[Downloadlink]</p>'),

(29, 'lastschrift', 'deu', '', '<p>Erm&auml;chtigung zum Einzug von Forderungen durch Lastschriften<br /><br />Einzugserm&auml;chtigung: Hiermit erm&auml;chtige(n) ich/wir Sie widerruflich, die von mir/uns zu entrichtenden Zahlungen zu Gunsten von [Firmenname] bei F&auml;lligkeit zu Lasten meines/unseres Kontos durch Lastschrift einziehen zu lassen.<br />Im Falle von umstrittenen Forderungen k&ouml;nnen Sie die Abbuchungen bei dem kontof&uuml;hrenden Kreditinstitut widerrufen. Der Widerruf kann bis zu sechs Wochen nach der Abbuchung eingereicht werden.<br /><br />Die Forderungen entstehen durch den Kauf bei [Firmenname].</p>'),
(30, 'lastschrift', 'eng', '', '<p>Authorization to collect claims through direct debits<br /><br /></p><p>Direct debit authorization: I / we hereby revocably authorize you to have the payments to be made by me / us in favor of [Firmenname] debited from my / our account when they are due.<br />In the case of disputed claims, you can revoke the direct debits from the bank holding the account. The revocation can be submitted up to six weeks after the direct debit.</p><p>&nbsp;</p><p>The claims arise from the purchase from [Firmenname].</p>'),

(31, 'anmeldung_nl', 'deu', 'Anmeldung Newsletter', '<p>Auf unserer Website [Shop-Domain] haben Sie uns folgende Einwilligung erteilt:<br /><br />&bdquo;Hiermit willige ich ein, dass ich den Newsletter mit Gutscheinen und sonstigen Aktionen von [Shopname] erhalte. Dieser Einwilligung kann ich jederzeit per E-Mail an [E-Mail] oder im Account widerrufen.".<br /><br />Hier verifizieren Sie Ihren Eintrag:<br />[Verifizierungslink]</p>'),
(32, 'anmeldung_nl', 'eng', 'Registration newsletter', '<p>You have given us the following consent on our website [Shop-Domain]:<br /><br />"I hereby consent to receiving the newsletter with coupon and other promotions from [Shopname]. I can revoke this consent at any time by email to [E-Mail] or in my account.".<br /><br />Verify your entry here:<br />[Verifizierungslink]</p>'),

(33, 'widerruf_dl_yes', 'deu', 'Ihre Bestellung bei [SHOPNAME]', '<p>Hallo [Anrede_Kunde] [Nachname_Kunde],<br /><br />hiermit bestätigen wir Ihren Wunsch, dass die Dienstleistung vor Ablauf der Widerrufsfrist beginnen soll.<br />Bei vollständiger Auftragserfüllung erlischt dass Widerrufsrecht.<br /><br />Viele Grüße<br />[SHOPINHABER]<br />[SHOPNAME]</p>'),
(34, 'widerruf_dl_yes', 'eng', 'Your order with [SHOPNAME]', '<p>Hello [Anrede_Kunde] [Nachname_Kunde],<br /><br />w<span class="tlid-translation translation" lang="en"><span title="">e hereby confirm your request that the service should begin before the withdrawal period has expired.</span><br /><span class="" title="">The withdrawal expires when the order is fully fulfilled.</span></span><br /><br />Best regards<br />[SHOPINHABER]<br />[SHOPNAME]</p>'),

(35, 'widerruf_dl_no', 'deu', 'Ihre Bestellung bei [SHOPNAME]', '<p>Hallo [Anrede_Kunde] [Nachname_Kunde],<br /><br/>hiermit bestätigen wir Ihren Wunsch, dass die Dienstleistung erst <strong>NACH</strong> Ablauf der Widerrufsfrist beginnen soll.<br />Sollte dies ein Versehen sein, nehmen Sie bitte mit uns Kontakt auf.<br /><br />Viele Grüße<br />[SHOPINHABER]<br />[SHOPNAME]</p>'),
(36, 'widerruf_dl_no', 'eng', 'Your order at [SHOPNAME]', '<p>Hello [Anrede_Kunde] [Nachname_Kunde],<br /><br />we hereby confirm your request that the service should only begin <strong>AFTER</strong> the cancellation period has expired.<br />If this is an oversight, please contact us.<br /><br />Best regards<br />[SHOPINHABER]<br />[SHOPNAME]</p>'),

(37, 'newsletter', 'deu', '', '<p>Hiermit willige ich ein, dass ich den Newsletter mit Gutscheinen und sonstigen Aktionen von [Shopname] erhalte. Dieser Einwilligung kann ich jederzeit per E-Mail an [E-Mail] oder im Account widerrufen</p>'),
(38, 'newsletter', 'eng', '', '<p>I hereby consent to receiving the newsletter with coupons and other promotions from [Shopname]. I can revoke this consent at any time by email to [E-Mail] or in my account.</p>');
